apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:   # this help service to match the exactly labels 
  selector:
    course: devops
    time: 4months 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     course: "devops"
     time: "4months"
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        
