apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    project: roboshop 
    tier: db 
    component : mongodb 
spec:
  replicas: 1
  selector:
    matchLabels:
      project : roboshop 
      tier : db 
      component : mongodb
  template:
    metadata:
      labels:
        project: roboshop
        tier : db 
        component : frontend 
    spec:
      containers:
      - name: mongodb 
        image: shaikaliasif/mongodb:1.0.0 

        
