apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:  # these labels are replicaset labels
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      project: expense 
      envrionment: dev 
      tier: frontend
  template:
    metadata:
      labels:
        project: expense 
        envrionemnt: dev
        tier: frontend 
    spec:
      containers:
      - name: 

